CREATE TABLE refund_comments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  refund_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  comment TEXT NOT NULL,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
